import React,{useMemo,useState} from 'react'
import { Activity, Stamp, CheckCircle2, AlertTriangle, ShieldCheck, Search, Clock3, Route, FileText, LayoutGrid } from 'lucide-react'
import { Kpi, Panel, StatusBadge, SlaBadge, Badge, RouteStrip, Empty } from '../components/ui'
import { PROFILES, officeName } from '../data/catalogs'
import { slaInfo } from '../workflowEngine'

export default function AdminControlView({items,offices,setActiveView}){
  const active=items.filter(x=>!['FINALIZADO','SOLICITUD_VIRTUAL'].includes(x.estado)),finalized=items.filter(x=>x.estado==='FINALIZADO'),observed=items.filter(x=>x.estado==='OBSERVADO')
  const overdue=items.filter(x=>slaInfo(x)?.overdue)
  const [query,setQuery]=useState('')
  const rows=useMemo(()=>active.filter(x=>`${x.numero||x.tracking} ${x.solicitante} ${x.asunto}`.toLowerCase().includes(query.toLowerCase())),[active,query])
  const officeLoad=offices.filter(o=>!['mesa_partes','direccion'].includes(o.id)).map(o=>({office:o,count:items.filter(x=>x.oficinaActual===o.id&&['EN_OFICINA','OBSERVADO'].includes(x.estado)).length}))
  return <div className="role-page">
    <div className="hero-row"><div><span className="eyebrow">ADMINISTRADOR</span><h1>Centro de control de Mesa de Partes</h1><p>Monitorea expedientes, carga por oficina, incidencias y configuración del proceso desde una sola vista.</p></div><button className="btn primary big" onClick={()=>setActiveView('workflow')}><Route size={18}/> Administrar rutas</button></div>
    <div className="kpi-grid five"><Kpi label="Activos" value={active.length} helper="En proceso" icon={Activity}/><Kpi label="Dirección" value={items.filter(x=>x.estado==='EN_DIRECCION').length} helper="Esperando proveído" icon={Stamp} tone="orange"/><Kpi label="Observados" value={observed.length} helper="Requieren subsanación" icon={AlertTriangle} tone="pink"/><Kpi label="Vencidos" value={overdue.length} helper="Fuera de SLA" icon={Clock3} tone="pink"/><Kpi label="Finalizados" value={finalized.length} helper="Cerrados" icon={CheckCircle2} tone="green"/></div>
    <div className="admin-two-col"><Panel title="Monitor en vivo" subtitle="Expedientes activos y punto exacto del recorrido." actions={<div className="search-mini"><Search size={15}/><input value={query} onChange={e=>setQuery(e.target.value)} placeholder="Buscar…"/></div>}><div className="monitor-list">{rows.length?rows.map(x=><div className="monitor-row" key={x.id}><div className="monitor-id"><b>{x.numero?`EXP ${x.numero}`:x.tracking}</b><StatusBadge status={x.estado}/><SlaBadge exp={x}/><span>{x.asunto}</span></div><div className="monitor-route"><RouteStrip exp={x} compact/></div><div className="monitor-owner"><span>Actual</span><b>{officeName(x.oficinaActual)}</b></div></div>):<Empty/>}</div></Panel>
      <Panel title="Carga por oficina" subtitle="Permite identificar dónde se acumulan expedientes."><div className="office-load">{officeLoad.map(({office,count})=><div key={office.id}><span className="office-color" style={{background:office.color}}></span><b>{office.name}</b><div className="load-bar"><i style={{width:`${Math.min(100,count*28)}%`,background:office.color}}></i></div><strong>{count}</strong></div>)}</div></Panel></div>
    <div className="admin-three"><button className="admin-card" onClick={()=>setActiveView('workflow')}><Route size={21}/><div><b>Trámites y rutas</b><span>Diseñador visual, versiones y simulación.</span></div></button><button className="admin-card" onClick={()=>setActiveView('book')}><FileText size={21}/><div><b>Libro y auditoría</b><span>Registro oficial y trazabilidad.</span></div></button><button className="admin-card" onClick={()=>setActiveView('catalog')}><LayoutGrid size={21}/><div><b>Oficinas y trámites</b><span>{PROFILES.length} perfiles demo · {offices.length} oficinas configuradas.</span></div></button></div>
    <Panel title="Modelo de autorización del prototipo" subtitle="En producción: rol + oficina + permisos. Dirección y oficinas son perfiles operativos, no deben hardcodearse en el frontend."><div className="permission-matrix">{PROFILES.map(p=><div key={p.id}><div><ShieldCheck size={16}/><b>{p.label}</b><span>{p.role}{p.office?` · ${officeName(p.office)}`:''}</span></div><div className="permission-tags">{p.permissions.slice(0,4).map(x=><Badge key={x} tone="neutral">{x}</Badge>)}</div></div>)}</div></Panel>
  </div>
}
