import React,{useMemo,useState} from 'react'
import { Search, Download, BookOpen, FileText } from 'lucide-react'
import { Panel, StatusBadge, SlaBadge, Badge, Empty, Timeline } from '../components/ui'
import { officeName } from '../data/catalogs'
import { slaInfo } from '../workflowEngine'
export default function BookAuditView({items}){
  const [q,setQ]=useState(''),[selectedId,setSelectedId]=useState(null)
  const rows=useMemo(()=>items.filter(x=>x.numero).filter(x=>`${x.numero} ${x.solicitante} ${x.asunto} ${x.estado}`.toLowerCase().includes(q.toLowerCase())).sort((a,b)=>b.numero-a.numero),[items,q])
  const selected=items.find(x=>x.id===selectedId)||rows[0]
  const exportCsv=()=>{const header=['N Exp','Fecha','Hora','Tipo Doc','Solicitante','Asunto','Folios','Firma Secretaria','VB Direccion','Oficina actual','Estado','Vencido SLA'];const data=rows.map(x=>[x.numero,x.fecha,x.hora,x.tipoDocumento,x.solicitante,x.asunto,x.numeroFolios,x.firmaSecretaria,x.vistoBuenoDireccion,officeName(x.oficinaActual),x.estado,slaInfo(x)?.overdue?'Sí':'No']);const csv=[header,...data].map(r=>r.map(v=>`"${String(v||'').replaceAll('"','""')}"`).join(',')).join('\n');const a=document.createElement('a');a.href=URL.createObjectURL(new Blob([csv],{type:'text/csv'}));a.download='Libro_Mesa_Partes_ARIB.csv';a.click()}
  return <div className="role-page"><div className="hero-row"><div><span className="eyebrow">LIBRO DIGITAL Y AUDITORÍA</span><h1>Registro oficial de expedientes</h1><p>Digitaliza los campos del libro físico y conserva el historial completo de cada movimiento.</p></div><button className="btn soft big" onClick={exportCsv}><Download size={18}/> Exportar CSV</button></div><div className="book-layout"><Panel title="Libro de Mesa de Partes" actions={<div className="search-mini"><Search size={15}/><input value={q} onChange={e=>setQ(e.target.value)} placeholder="Buscar expediente…"/></div>}><div className="table-wrap"><table><thead><tr><th>N.° Exp</th><th>Fecha/Hora</th><th>Tipo</th><th>Nombres / Razón social</th><th>Asunto</th><th>Folios</th><th>Firma Sec.</th><th>V°B° Dir.</th><th>Oficina</th><th>Estado</th><th>SLA</th></tr></thead><tbody>{rows.map(x=><tr key={x.id} className={selected?.id===x.id?'selected':''} onClick={()=>setSelectedId(x.id)}><td><b>{x.numero}</b></td><td>{x.fecha}<br/><span>{x.hora}</span></td><td>{x.tipoDocumento}</td><td>{x.solicitante}</td><td>{x.asunto}</td><td>{x.numeroFolios}</td><td>{x.firmaSecretaria?'✓':'—'}</td><td>{x.vistoBuenoDireccion?'✓':'—'}</td><td>{officeName(x.oficinaActual)}</td><td><StatusBadge status={x.estado}/></td><td><SlaBadge exp={x}/></td></tr>)}</tbody></table></div></Panel><Panel title={selected?`Auditoría EXP ${selected.numero}`:'Auditoría'} subtitle="Quién hizo qué, cuándo y desde qué punto del proceso.">{selected?<><div className="audit-summary"><Badge tone="info">{selected.canal}</Badge><Badge tone="neutral">Ruta v{selected.routeVersion||'—'}</Badge><span>{selected.solicitante}</span></div><Timeline items={selected.historial}/></>:<Empty/>}</Panel></div></div>
}
