import React,{useState} from 'react'
import { Search, Route, FileText, UserRound } from 'lucide-react'
import { Panel, StatusBadge, SlaBadge, Badge, RouteStrip, Timeline, Empty, FileList } from '../components/ui'
export default function TrackingView({items}){
  const [q,setQ]=useState('5225'),[selectedId,setSelectedId]=useState(null)
  const results=items.filter(x=>`${x.numero||''} ${x.tracking} ${x.solicitante} ${x.dni}`.toLowerCase().includes(q.toLowerCase()))
  const selected=items.find(x=>x.id===selectedId)||results[0]
  return <div className="role-page"><div className="hero-row"><div><span className="eyebrow">SEGUIMIENTO</span><h1>Consulta de expediente</h1><p>Busca por N.° expediente, código temporal, solicitante o DNI.</p></div></div><div className="tracking-search"><Search size={19}/><input value={q} onChange={e=>setQ(e.target.value)} placeholder="Ej. 5225, ARIB-5225 o DNI…"/></div><div className="tracking-grid"><Panel title="Resultados"><div className="case-list">{results.length?results.map(x=><button key={x.id} className={`case-item ${selected?.id===x.id?'active':''}`} onClick={()=>setSelectedId(x.id)}><div className="case-icon"><Route size={18}/></div><div className="case-main"><div><b>{x.numero?`EXP ${x.numero}`:x.tracking}</b><StatusBadge status={x.estado}/></div><strong>{x.asunto}</strong><span>{x.solicitante}</span></div></button>):<Empty title="Sin coincidencias" text="Prueba con otro número o nombre."/>}</div></Panel><Panel title={selected?`${selected.numero?`EXP ${selected.numero}`:selected.tracking} · ${selected.asunto}`:'Detalle'}>{selected?<div className="case-detail"><div className="detail-top"><StatusBadge status={selected.estado}/><SlaBadge exp={selected}/><Badge tone="neutral">{selected.canal}</Badge></div><h4>Recorrido</h4><RouteStrip exp={selected}/><div className="detail-cols"><div><span>Solicitante</span><b>{selected.solicitante}</b></div><div><span>DNI</span><b>{selected.dni}</b></div><div><span>Fecha</span><b>{selected.fecha}</b></div><div><span>Folios</span><b>{selected.numeroFolios}</b></div></div><h4>Adjuntos</h4><FileList files={selected.adjuntos}/><h4>Historial</h4><Timeline items={selected.historial}/></div>:<Empty/>}</Panel></div></div>
}
